version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo start prebuild
      - ECR_PASSWORD=$(aws ecr get-login-password --region ap-northeast-1)
      - docker login --username AWS --password-stdin $ECR_PASSWORD 027364171510.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPO=$(aws ecr describe-repositories --repository-names terraform-lesson-dev-ecr --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"terraform-lesson-dev-ecr","iamgeUri":"%s"}]' $IMAGE > imagedefinition.json
artifacts:
  files: imagedefinition.json
