version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo start prebuild
      # ecr login
      - docker info
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 027364171510.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPO=$(aws ecr describe-repositories --repository-names terraform-lesson-dev-ecr --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
      # gradle build
      - ./gradlew build -x test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $IMAGE
      - docker build -t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"terraform-lesson-dev-ecr","imageUri":"%s"}]' $IMAGE > imagedefinition.json
artifacts:
  files: imagedefinition.json
